baseURL: "https://merlinds.github.io/"
languageCode: "en-us"
title: "MerlinDS"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

# Menus:
  # main:
    # - identifier: blog
    #   name: Blog
    #   title: Blog posts
    #   url: /blogs
    #   weight: 1
    # - identifier: gallery
    #   name: Gallery
    #   title: Blog posts
    #   url: /gallery
    #   weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "MerlinDS"
  description: This site is a personal portfolio and blog of Andrew Salomatin. 
  # staticPath: ""  # The path to serve the static files from
  # favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # When using hex codes for colors, quotations must be used along with the # sign
  # color:
  #   textColor: "#343a40"
  #   secondaryTextColor: "#6c757d"
  #   backgroundColor: "#eaedf0"
  #   secondaryBackgroundColor: "#64ffda1a"
  #   primaryColor: "#007bff"
  #   secondaryColor: "#f8f9fa"

  #   darkmode:
  #     textColor: "#e4e6eb"
  #     secondaryTextColor: "#b0b3b8"
  #     backgroundColor: "#18191a"
  #     secondaryBackgroundColor: "#212529"
  #     primaryColor: "#ffffff"
  #     secondaryColor: "#212529"

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "MerlinDS" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    enableSeparator: false
    menus:
      disableAbout: false
      disableExperience: false
      disableProjects: false
      disableContact: true
      disableEducation: true
      disableAchievements: true

  # Hero
  hero:
    enable: false
    intro: "Hi, my name is"
    title: "Isabella."
    subtitle: "I build things for the web"
    content: "A passionate web app developer. I tend to make use of modern web technologies to build websites that looks great, feels fantastic, and functions correctly."
    image: /merlinds/images/hero.svg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://example.com
        - icon: fab fa-x-twitter
          url: https://example.com
      customIcons:
        - icon: /fav.png
          url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/merlinds/images/me.png"
    content: |-
      Hi there! 👋 My name is Andrew and I’m a software engineer with a huge passion for game development. I prefer to work with Unity and C#, especially with the new DOTS framework, but I'm always open to learning new technologies. I have over 14 years of experience in the game development industry, working on various projects from PC and mobile to social and browser-based games.
      
      Currently, I am working on a turn-based strategy called "Rebecca’s Flight" as a lead software developer at the "The End of Time Studio".
    skills:
      enable: true
      title: "Here are a few of my skills:"
      items:
        - "Unity"
        - "C#"
        - "OOP"
        - "ECS"
        - "Git"
        - "DOTS"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Lead Software Developer"
        company: "TEOTS"
        companyUrl: "https://rebeccasflight.com"
        date: "Feb 2018 - Present"
        info:
          enable: true
          content: 6 and a half years.
        content: |
          I am currently working as a lead software developer at "The End of Time Studio" in Kyiv, Ukraine. 
          We are developing a game called "Rebecca's Flight" which is a turn-based strategy game set in a space opera universe.
          
          - Developing the game's core mechanics.
          - Implementing the game's AI.
          - Working with the game's artists to implement their assets.
          
      - job: "Software Developer"
        company: "Playtagon"
        date: "May 2016 - Jun 2017"
        info:
          enable: true
          content: 1 year and 2 months.
        content: |
            I worked as a software developer at "Playtagon" in Kyiv, Ukraine. 
            Developed a mobile game called "Hero Rage" which is a fast-paced multiplayer action game, for iOS and Android.
            
            My responsibilities included:
            - Developed the system of character skinning.
            - Development and implementation of the audio engine.
            - Implementation of various analytical services and the collection of statistical data for them: FuseBoxx, DeltaDNA, Adjust, Flury, etc.
            - Integration of new UI elements and animations.
          
      - job: "Software Developer"
        company: "Win Interactive"
        companyUrl: "https://www.win-interactive.com/en/"
        date: "Jun 2010 - May 2014"
        info:
          enable: true
          content: 4 years.
        content: | 
            Designed and developed heavily loaded mobile games for iOS, Android and social networks. Using AIR, Starling and Feathers.
            Developed social games for Facebook platform.
          
      - job: "Junior Software Developer"
        company: "NAGLO Entertainment"
        date: "Nov 2008 - Aug 2009"
        info:
          enable: true
          content: 10 months.
        content: |
          Developed flash client for MMORPG game "Apocalypse 2056". 
          Developed 2.5D engine that draws animations using PixelBlender and allows changing skins of characters without the need for reloading a large graphics resources. 
          Created a framework for downloading graphics resources using Flash Player local cache mechanism.

  # Education
  education:
    enable: false
    # title: "Custom Name"
    index: false
    items:
      - title: "Master of Business Administration"
        school:
          name: "University of California, Berkeley"
          url: "https://example.org"
        date: "2013 - 2015"
        GPA: "3.8 out of 5.0"
        content: |-
          Extracurricular Activities
            - Lorem ipsum dolor sit amet consectetur adipisicing elit.
            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
      - title: "Bachelor of Science in Computer Science"
        school:
          name: "Massachusetts Institute of Technology"
          url: "https://example.org"
        date: "2009 - 2013"
        GPA: "3.9 out of 5.0"
        content: |-
          I Publiced two papers in the ACM SIGCHI Conference on Artificial Intelligence.
          - [Fast and Accurate Object Detection with a Single Convolutional Neural Network](https://example.com)
          - Face mask detection using a single convolutional neural network.

          Extracurricular Activities
            - Lorem ipsum dolor sit amet consectetur adipisicing elit.
            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
        featuredLink:
          enable: true
          name: "My academic record"
          url: "https://example.com"
      - title: "High School"
        school:
          name: "Thomas Jefferson High School for Science and Technology."
          url: "https://example.org"
        GPA: "4.2 out of 5.0"
        featuredLink:
          enable: true
          url: "https://example.com"

  # Achievements
  achievements:
    enable: false
    # title: "Custom Name"
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
        image: /images/achievment.jpg
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
        image: /images/achievment.jpg
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
        image: /images/achievment.jpg
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Rebecca's Flight
        content: The turn-based strategy game set in a space opera universe.
        image: /images/projects/rebeccas-flight.jpg
        featured:
          name: Website
          link: https://rebeccasflight.com
        badges:
          - "Unity"
          - "C#"
          - "ECS"
          - "DOTS"
        links:
          - icon: fa fa-globe
            url: https://rebeccasflight.com
          - icon: fab fa-youtube
            url: https://www.youtube.com/channel/UCuGT5ZUdhSr95Hpfqr2dfxQ
          - icon: fab fa-twitter
            url: https://twitter.com/rebeccasflight
      
      - title: Hero Rage
        content: The fast-paced multiplayer action game for iOS and Android.
        image: /images/projects/hero-rage.jpg
        featured:
          name: Video
          link: https://www.youtube.com/watch?v=xKIZqwGbTgo
        badges:
          - "Unity"
          - "C#"
          - "Photon"
              
      - title: Bubbly Tap
        content: The hyper-casual logic puzzle game for Android.
        image: /images/projects/bubbly-tap.png
        featured:
          name: Video
          link: https://www.moddb.com/games/bubbly-tap/videos/bubbly-tap-trailer1
        badges:
          - "Unity"
          - "C#"
          - "DOTS"
              
      - title: Loony Quack
        content: The hyper-casual arcade game for Android.
        image: /images/projects/loony-quack.png
        badges:
          - "Flash"
          - "ActionScript"
          - "AIR"
        featured:
          name: Video
          link: https://youtu.be/h9_qoeVN11U
              
      - title: Slot Craze
        content: The social casino game for mobile and Facebook.
        image: /images/projects/slot-craze.jpg
        badges:
          - "Flash"
          - "ActionScript"
          - "AIR"
        featured:
          name: Android
          link: https://play.google.com/store/apps/details?id=air.com.luckgenome.SlotsCrazeAndroid&hl=en
              
      - title: Apocalypse 2056
        content: The browser-based MMORPG game with 2.5D visuals.
        image: /images/projects/apocalypes-2056.jpg
        badges:
          - "Flash"
          - "ActionScript"
          - "PixelBlender"

  #Contact
  contact:
    enable: false
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    btnName: Mail me
    btnLink: mailto:andy.salomatin@gmail.com
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"
    #   messageRows: 5

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: false
      disableFeaturedImage: true
    socialNetworks:
      github: https://github.com/MerlinDS
      linkedin: https://www.linkedin.com/in/merlinds
      instagram: https://www.instagram.com/merlinds

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    socialShare: true
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true
    tags:
      openInNewTab: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "22 Jun 2024"
    articleList: "22 Jun 2024"
    articleRecent: "22 Jun 2024"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
